import { Counselor } from '@/types';

export const INITIAL_COUNSELORS: Counselor[] = [
  {
    id: 'c1',
    fullName: 'Dr. Jasur Mansurov',
    headline: 'Cardiologist & Medical Residency Mentor | Ex-Ankara Hospital',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop',
    specialties: ['Medicine & Healthcare', 'Residency in Turkey & Germany', 'Clinical Research'],
    bio: 'Guiding medical students and young doctors through clinical residency exams abroad, licensing roadmaps, and choosing medical specialties.',
    standardPrice: 45000,
    premiumPrice: 130000,
    rating: 4.9,
    reviewsCount: 38,
    availableSlots: [
      'Saturday, 15:00 - 15:30',
      'Saturday, 16:00 - 16:30',
      'Sunday, 11:00 - 11:30',
    ],
  },
  {
    id: 'c2',
    fullName: 'Madina Shodieva',
    headline: 'Lead Architect & Interior Designer | Studio Founder',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop',
    specialties: ['Architecture & Design', 'Portfolio Review', 'Freelance & Studio Launch'],
    bio: '8+ years designing commercial and residential spaces across Central Asia. I review student portfolios and advise on landing clients.',
    standardPrice: 40000,
    premiumPrice: 120000,
    rating: 5.0,
    reviewsCount: 29,
    availableSlots: [
      'Friday, 18:00 - 18:30',
      'Saturday, 12:00 - 12:30',
      'Sunday, 14:00 - 14:45',
    ],
  },
  {
    id: 'c3',
    fullName: 'Otabek Rustamov',
    headline: 'International Corporate Lawyer | LL.M. Leiden University',
    avatarUrl: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?w=400&h=400&fit=crop',
    specialties: ['Law & Legal Practice', 'International LL.M.', 'Corporate Law Career'],
    bio: 'Assisting law students in navigating international master’s applications, bar preparation, and building a corporate legal career in Tashkent.',
    standardPrice: 50000,
    premiumPrice: 150000,
    rating: 4.8,
    reviewsCount: 22,
    availableSlots: [
      'Saturday, 10:00 - 10:30',
      'Sunday, 17:00 - 17:30',
    ],
  },
  {
    id: 'c4',
    fullName: 'Kamila Yusupova',
    headline: 'Fulbright Alumna | Education & Global Scholarships Coach',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop',
    specialties: ['Study Abroad', 'Scholarship Essays', 'IELTS & GRE Strategy'],
    bio: 'Assisted 40+ students in securing fully-funded Master’s scholarships in the US, Europe, and Asia. Specialist in personal statement coaching.',
    standardPrice: 45000,
    premiumPrice: 140000,
    rating: 4.9,
    reviewsCount: 45,
    availableSlots: [
      'Monday, 19:00 - 19:30',
      'Thursday, 19:00 - 19:30',
      'Saturday, 11:00 - 11:45',
    ],
  },
  {
    id: 'c5',
    fullName: 'Sardor Ergashev',
    headline: 'Agribusiness & Export Director | Regional Trade Advisor',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    specialties: ['Agriculture & Trade', 'Export Logistics', 'Starting a Business'],
    bio: 'Helping young entrepreneurs understand agricultural supply chains, food processing, export regulations, and starting regional ventures.',
    standardPrice: 40000,
    premiumPrice: 110000,
    rating: 4.9,
    reviewsCount: 16,
    availableSlots: [
      'Saturday, 13:00 - 13:30',
      'Sunday, 15:00 - 15:30',
    ],
  },
  {
    id: 'c6',
    fullName: 'Azizbek Kholmatov',
    headline: 'Principal Software Architect | Tech Mentor',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    specialties: ['Engineering & Tech', 'System Design', 'Tech Interview Prep'],
    bio: '10+ years engineering large-scale distributed systems. Mentoring engineers from junior to senior and preparing for global tech interviews.',
    standardPrice: 50000,
    premiumPrice: 160000,
    rating: 5.0,
    reviewsCount: 52,
    availableSlots: [
      'Saturday, 16:00 - 16:30',
      'Sunday, 10:00 - 10:45',
    ],
  },
];